trigger:
  branches:
    include:
      - dev   # pipeline triggers only on dev branch

pool:
  vmImage: 'windows-selfhosted-pool'

steps:
- script: |
    echo "Pipeline triggered from GitHub dev branch"
    echo "Listing files:"
    ls -l
  displayName: 'Run sample script'

